# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAfV8Yw1EqnHdbFzrKxnEcFLqQoPGY4i
"""

# streamlit_app.py



st.title("こんにちは！")
st.write("初めまして！これは最初のStreamlitアプリです。")
import streamlit as st
import pandas as pd

# サンプルデータ
data = {
    "銘柄": ["AAPL", "MSFT", "NVDA"],
    "AIターゲット": [250, 380, 1000],
    "現在価格": [220, 340, 850]
}
df = pd.DataFrame(data)

# タイトル
st.title("AI株価ターゲット一覧")

# 表の表示
st.dataframe(df)

# 差分チャート
st.bar_chart(df["AIターゲット"] - df["現在価格"])
