# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAfV8Yw1EqnHdbFzrKxnEcFLqQoPGY4i
"""

# streamlit_app.py

import streamlit as st

st.title("こんにちは！")
st.write("これは最初のStreamlitアプリです。")
import streamlit as st
import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# タイトル
st.title("📈 株価チャート＆AI予測デモ")

# 株価コードの入力
ticker = st.text_input("ティッカーシンボルを入力してください（例：AAPL, MSFT, TSLA）", "AAPL")

# 日付範囲の選択
days = st.slider("何日分のデータを表示しますか？", 30, 365, 180)

# データ取得
if ticker:
    end_date = datetime.today()
    start_date = end_date - timedelta(days=days)

    try:
        data = yf.download(ticker, start=start_date, end=end_date)
        st.write(f"表示中：{ticker} の株価データ（{start_date.date()}～{end_date.date()}）")

        # チャート表示
        fig, ax = plt.subplots()
        ax.plot(data.index, data['Close'], label='終値')
        ax.set_title(f"{ticker} 株価チャート")
        ax.set_xlabel("日付")
        ax.set_ylabel("価格（USD）")
        ax.legend()
        st.pyplot(fig)

    except Exception as e:
        st.error(f"データ取得に失敗しました: {e}")
import streamlit as st
import yfinance as yf

st.title("株価チャートビューア")

# ユーザーにティッカーと期間を入力させる
ticker = st.text_input("ティッカーシンボルを入力してください（例：AAPL、GOOG、MSFT）", "AAPL")

# 期間の選択肢を追加
period = st.selectbox(
    "表示期間を選択してください",
    ("1mo", "3mo", "6mo", "1y", "2y", "5y", "10y", "max"),
    index=2  # デフォルトは「6ヶ月」
)

# 株価データを取得して表示
if ticker:
    try:
        data = yf.Ticker(ticker).history(period=period)
        if not data.empty:
            st.subheader(f"{ticker} の {period} の終値チャート")
            st.line_chart(data['Close'])
        else:
            st.warning("データが見つかりませんでした。ティッカーが正しいか確認してください。")
    except Exception as e:
        st.error(f"データ取得中にエラーが発生しました: {e}")
