# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAfV8Yw1EqnHdbFzrKxnEcFLqQoPGY4i
"""

# streamlit_app.py

import streamlit as st

st.title("こんにちは！")
st.write("初めまして。これは最初のStreamlitアプリです。")
